name: Ubuntu compatibility

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build on ${{ matrix.runner }} (${{ matrix.php_image }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            php_image: 8.4-cli

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: false
          load: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_IMAGE=${{ matrix.php_image }}
